### ISSUE TITLE
Practical Tips - Slides?

### ISSUE THREAD

**Issue by kytrinyx** [janl/waaa#3]
There are 3 links that helped me figure out how to make better slides:

http://nubyonrails.com/articles/improve-your-technical-slides

http://zachholman.com/posts/slide-design-for-developers/

http://www.slideshare.net/veganstraightedge/gogaruco-2010-lightening-talk-better-slides

Also, I've been working on a keynote color palette and pygments colorscheme for generating syntax highlighted code in .rtf format that will work well on a projector -- in case that's of any interest (https://github.com/kytrinyx/talkode)

Would you be interested a little section on the 'practical tips' page? I'd be happy to add one.

**Comment by janl** [comment]
That sounds all great, I'd say keep the pull requests coming :)

**Comment by theophani** [comment]
First, thanks a bunch for those great updates so far :). Thanks a lot for being awesome. I loved that Nancy Duarte talk.

Re these links: Great selection :)

I want to have a page dedicated just to slides. I have some notes of my own on that topic already, not committed.

I'm headed to bed, so if you want to create a rough version of that page, do, otherwise I'll add these resources to the slides page when I start it.

Thanks again!
-t

**Comment by kytrinyx** [comment]
I'm heading off to NordicRuby in a couple hours, need to get some work-work done first. If you haven't got anything when I'm back from the conference I'll put together a draft.

Sweet!

**Comment by theophani** [comment]
I pulled in your "draft" as you called it, since what you had so far was great. It likely needs more tips. Thanks for this, and the other work you did last night / today.
